% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created 06-May-2016 11:56:51
%
% This script assumes these variables are defined:
%
%   cancerInputs - input data.
%   cancerTargets - target data.

x = pimaindiansdiabetes';
t = position;
%x = cancerInputs;
%t = cancerTargets;

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'traingd';  % Scaled conjugate gradient backpropagation.

% Create a Pattern Recognition Network
hiddenLayerSize = 8;

net = patternnet(12);
net = configure(net, x, t);
net.trainFcn = 'traingd';
net.trainParam.lr = 0.5;
%net.trainParam.max_fail = 50;
net.trainParam.epochs = 5000;

% Setup Division of Data for Training, Validation, Testing
net.divideFcn = 'divideind';
net.divideParam.trainInd=1:500;
%net.divideParam.valInd=401:500;
net.divideParam.testInd=501:768;
%net = init(net);

% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y);
tind = vec2ind(t);
yind = vec2ind(y);
%percentErrors = sum(tind ~= yind)/numel(tind);

% View the Network
view(net)

%calculate error
for i = 1:768
    if (y(i) < 0.5) && (y(i) > 0)
        y(i) = 0;
    elseif (y(i) > 0.5) && (y(i) <= 1)
        y(i) = 1;
    else
        y(i) = -1;
    end
end
trainErrNum = 0;
testErrNum = 0;
for i = 1:500
    if y(i) ~= t(i)
        trainErrNum = trainErrNum+1;
    end
end
for i = 501:768
    if y(i) ~= t(i)
        testErrNum = testErrNum+1;
    end
end
trainErrPercent = trainErrNum/500
testErrNum = testErrNum/276
% Plots
% Uncomment these lines to enable various plots.
figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotconfusion(t,y)
%figure, plotroc(t,y)

